In [72]:
import h5py
import numpy as np
import pandas as pd
from math import *
import operator

In [128]:
data = "enron"
d=37
feature = ""
feature2 = "_gram"

In [129]:
f = open("feature_data_"+data+feature+".txt", "r")
base = f.read()
base_temp = base.split(' ')

In [130]:
base = base_temp[:-1]
base_arr = []
for item in base:
    base_arr.append(2*float(item))

base = np.array(base_arr)

In [131]:
base = np.reshape(base,(int(base.shape[0]/d),d))
base.shape

(244345, 37)

In [132]:
print("feature_queries_"+data+feature+".txt")
f = open("feature_queries_"+data+feature+".txt", "r")
query = f.read()
query_temp = query.split(' ')
query = query_temp[:-1]

query_arr = []
for item in query:
    query_arr.append(2*float(item))

query = np.array(query_arr)

feature_queries_enron.txt


In [133]:
query = np.reshape(query,(int(query.shape[0]/d),d))
query.shape

(1000, 37)

In [134]:
query[409]/2

array([ 3.,  4.,  1.,  1., 21., 23.,  0., 11., 18., 14., 53.,  5., 20.,
       11.,  5., 20.,  9.,  0.,  0., 12.,  8.,  5.,  7.,  7.,  0.,  3.,
       12.,  3.,  2.,  0.,  1.,  0.,  6.,  0.,  0.,  0.,  0.])

In [135]:
query[-1]/2

array([ 3.,  4.,  1.,  1., 21., 23.,  0., 11., 18., 14., 53.,  5., 20.,
       11.,  5., 20.,  9.,  0.,  0., 12.,  8.,  5.,  7.,  7.,  0.,  3.,
       12.,  3.,  2.,  0.,  1.,  0.,  6.,  0.,  0.,  0.,  0.])

In [111]:
test = open("idec_results/iDEC_result"+feature2+".txt", "r")
res = test.read()
res_temp = res.split(' ')

In [112]:
res = res_temp[:-1]

In [113]:
def cal_l1(bid,qid):
    return abs(base[bid]-query[qid]).sum()

In [114]:
len(res)/1000

60000.0

In [162]:
t_idec=int(len(res)/1000)
k=10100

In [163]:
result = []
for i in range(1000):
    top = {}
    for t in range(k):
        l1_dist = cal_l1(int(res[i*t_idec+t]),i)
        top.update({int(res[i*t_idec+t]):l1_dist})
                
        
    top = dict(sorted(top.items(), key=operator.itemgetter(1)))
    temp = list(top.keys())
    
    result.extend(temp)

In [164]:
len(result)

10400000

In [165]:
import os
os.remove("result.txt")

In [166]:
f = open("result.txt", "w")
for item in result:
    f.write(str(item)+'\n')

f.close()

In [ ]:
base.flatten()

In [ ]:
query.shape[0]/23

In [26]:
f_write.close()

In [29]:
sqrt(3000)*4

219.08902300206645

In [ ]:
110

In [30]:
220-110

110

In [43]:
file = h5py.File('enron-utf8-vlen.h5','r')
distance = file['distances'][:][:]

In [44]:
distance[409]

array([155., 174., 180., 181., 181., 182., 186., 187., 188., 189.])

In [45]:
distance[-1]

array([155., 174., 180., 181., 181., 182., 186., 187., 188., 189.])

In [167]:
f = open("result_distance.txt", "r")
str_result = f.readlines()

result_temp = []
for item in str_result:
    result_temp.append(int(item.split('\n')[0]))
    
len(result_temp)

cnt = 0
for i in range(1000):
    if result_temp[i] <= 1.3*distance[i][0]:
        cnt = cnt+1
        
cnt*1.0/1000

0.906

In [51]:
file = 0

In [163]:
18000/180742.557*15.7

1.5635498616963797

In [10]:
file = h5py.File('enron-utf8-vlen.h5','r')
file.keys()

<KeysViewHDF5 ['alphabet', 'base', 'query']>

In [19]:
base = file['base'][:]
query = file['query'][:]

In [20]:
cnt = 0
for str_t in query:
    if len(str_t) <=11:
        cnt = cnt +1

In [21]:
cnt

1

In [6]:
file.close()

0.942

In [80]:
1.61244+1.14978+1.431755

4.193975

In [41]:
cnt = 0
for i in range(1000):
    if results[i] <= 1.3*distance[i][0]:
        cnt = cnt+1
        
cnt*1.0/1000

0.147

In [178]:
29.315913+1.76783+0.0088

31.092543

In [45]:
1.78+0.58+ 2.422429

4.7824290000000005

In [28]:
test = base[0+529:529+529]

In [29]:
base_arr =base.reshape((399000,529))

ValueError: cannot reshape array of size 12544256 into shape (399000,529)

In [30]:
base_arr[321313].sum()/2

AttributeError: 'float' object has no attribute 'sum'